apiVersion: v1
kind: ConfigMap
metadata:
  name: failover-config
  namespace: warehouse
data:
  failover.conf: |
    primary_region: ap-northeast-1
    backup_region: ap-northeast-2
    health_check_interval: 30s
    failover_threshold: 3
    automatic_failover: true
    notification_webhook: https://alerts.warehouse.com/webhook
    recovery_procedure:
      - validate_backup_region
      - switch_dns
      - promote_backup_db
      - update_application_config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: failover-controller
  namespace: warehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failover-controller
  template:
    metadata:
      labels:
        app: failover-controller
    spec:
      containers:
      - name: controller
        image: warehouse-failover:latest
        volumeMounts:
        - name: config
          mountPath: /etc/failover
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: secret-key
      volumes:
      - name: config
        configMap:
          name: failover-config 