apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-tuning
  namespace: warehouse
data:
  redis.conf: |
    # 内存管理
    maxmemory 2gb
    maxmemory-policy allkeys-lru
    
    # 持久化
    appendonly yes
    appendfsync everysec
    
    # 连接管理
    timeout 0
    tcp-keepalive 300
    maxclients 10000
    
    # 性能优化
    activerehashing yes
    no-appendfsync-on-rewrite yes
    
    # 快照配置
    save 900 1
    save 300 10
    save 60 10000 