apiVersion: v1
kind: ConfigMap
metadata:
  name: warehouse-config
  namespace: warehouse
data:
  ENVIRONMENT: production
  LOG_LEVEL: INFO
  BACKUP_RETENTION_DAYS: "7"
  RATE_LIMIT_PER_MINUTE: "60"
---
apiVersion: v1
kind: Secret
metadata:
  name: warehouse-secrets
  namespace: warehouse
type: Opaque
stringData:
  database-url: postgresql://user:password@db/warehouse_db
  redis-url: redis://redis:6379/0
  jwt-secret: your-jwt-secret-key
  aws-access-key: your-aws-access-key
  aws-secret-key: your-aws-secret-key 