apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-api
  namespace: warehouse
spec:
  replicas: 3
  selector:
    matchLabels:
      app: warehouse-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: warehouse-api
    spec:
      containers:
      - name: api
        image: warehouse-api:latest
        ports:
        - containerPort: 8000
        args:
        - --workers=4
        - --worker-class=uvicorn.workers.UvicornWorker
        - --max-requests=1000
        - --max-requests-jitter=50
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: warehouse-secrets
              key: database-url
        - name: REDIS_POOL_SIZE
          value: "20"
        - name: DB_POOL_SIZE
          value: "20"
        - name: DB_POOL_TIMEOUT
          value: "30"
        - name: WORKERS_PER_CORE
          value: "2"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 2
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - warehouse-api
              topologyKey: kubernetes.io/hostname 