apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: warehouse
data:
  postgresql.conf: |
    max_connections = 200
    shared_buffers = 1GB
    effective_cache_size = 3GB
    work_mem = 5242kB
    maintenance_work_mem = 256MB
    random_page_cost = 1.1
    effective_io_concurrency = 200
    wal_buffers = 16MB
    default_statistics_target = 100
    checkpoint_completion_target = 0.9
    autovacuum = on
    max_worker_processes = 8
    max_parallel_workers_per_gather = 4
    max_parallel_workers = 8 