apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: warehouse
data:
  redis.conf: |
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    appendonly yes
    save 900 1
    save 300 10
    save 60 10000
    tcp-keepalive 300
    timeout 0
    tcp-backlog 511
    databases 16 