apiVersion: v1
kind: Service
metadata:
  name: warehouse-api
  namespace: warehouse
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: warehouse-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: warehouse-ingress
  namespace: warehouse
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api.warehouse.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: warehouse-api
            port:
              number: 80 