apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: warehouse
data:
  elasticsearch.yml: |
    cluster.name: warehouse-logs
    node.name: ${HOSTNAME}
    network.host: 0.0.0.0
    discovery.type: single-node
    
    # 性能优化
    bootstrap.memory_lock: true
    indices.memory.index_buffer_size: 30%
    indices.queries.cache.size: 20%
    thread_pool.write.queue_size: 1000
    
    # 数据保留
    action.destructive_requires_name: true
    xpack.monitoring.enabled: true
    xpack.security.enabled: true 