apiVersion: v1
kind: Service
metadata:
  name: backup-restore
  namespace: warehouse
spec:
  selector:
    app: backup-restore
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-restore
  namespace: warehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup-restore
  template:
    metadata:
      labels:
        app: backup-restore
    spec:
      containers:
      - name: restore
        image: warehouse-restore:latest
        ports:
        - containerPort: 8080
        env:
        - name: AWS_S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: backup-secrets
              key: s3-bucket
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: backup-secrets
              key: aws-access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: backup-secrets
              key: aws-secret-key
        volumeMounts:
        - name: restore-volume
          mountPath: /restore
      volumes:
      - name: restore-volume
        emptyDir: {} 