apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: warehouse
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      slack_api_url: 'https://hooks.slack.com/services/YOUR-WEBHOOK-URL'
      wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=YOUR-KEY'

    route:
      group_by: ['alertname', 'severity']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: 'default-receiver'
      routes:
      - match:
          severity: critical
        receiver: 'critical-receiver'
        continue: true
      - match:
          severity: warning
        receiver: 'warning-receiver'

    receivers:
    - name: 'default-receiver'
      slack_configs:
      - channel: '#warehouse-alerts'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'

    - name: 'critical-receiver'
      slack_configs:
      - channel: '#warehouse-critical'
        send_resolved: true
        title: '[危急] {{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
      wechat_configs:
      - message_type: markdown
        message: '**[危急告警]**\n{{ template "wechat.default.message" . }}'

    templates:
    - '/etc/alertmanager/template/*.tmpl' 