apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: warehouse
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager:9093

    rule_files:
      - /etc/prometheus/rules/*.yml

    scrape_configs:
      - job_name: 'warehouse-api'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: keep
          regex: warehouse-api
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          action: keep
          regex: 8000 