apiVersion: v1
kind: ConfigMap
metadata:
  name: security-context-config
  namespace: warehouse
data:
  security-context.yaml: |
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault 